### PR TITLE
Fix: Support NetBox 4.6+ front/rear port mapping model

### PR DESCRIPTION
**Pull request by bklier-mpl**
## ⚠️ Breaking change
NetBox 4.6 replaced the direct `rear_port`/`rear_port_position` fields on front ports with a
separate `PortMapping` model, which doesn't exist on earlier NetBox versions. As a result,
**plugin 4.6.5 requires NetBox 4.6.0+ and no longer works on NetBox 4.3.1-4.5.x** (the range
supported by 4.5.8). This is called out in the updated `COMPATIBILITY.md` and `README.md`.

## Summary
- NetBox 4.6 replaced the direct `rear_port`/`rear_port_position` fields on `FrontPort`/`FrontPortTemplate` with a separate `PortMapping`/`PortTemplateMapping` model (accessible via the `mappings` related manager), which caused `FrontPortComparisonView` to raise `AttributeError: 'FrontPortTemplate' object has no attribute 'rear_port_position'`.
- Add a `get_rear_port_mapping()` helper that reads the rear port association through the new mapping model, and use it wherever the plugin previously read/wrote `rear_port_id`/`rear_port_position` directly on `FrontPort`(`Template`).
- When creating new front ports, a corresponding `PortMapping` row is now created to preserve the rear port association.
- Bump the declared version to 4.6.5 and extend the compatibility matrix.
- Drop the unused `numpy`/`requests` dependencies from `pyproject.toml`.
- Document the breaking change in `README.md` and point readers to `COMPATIBILITY.md` for the correct plugin/NetBox version pairing.

## Test plan
- [ ] Verify front port sync on a NetBox 4.6+ instance creates/updates front ports with correct rear port mappings
- [ ] Verify the plugin fails gracefully (or document that it's unsupported) on NetBox < 4.6, since this is now a breaking change

### CODE REVIEW

**Comment by drousseau** [comment]
Hi

We have Netbox installed with version 4.6.4 and we use this plugin, version 4.5.8 installed

I tried the fix, on a test instance, which seems to be working

We really wish a new version to be publisshed for our production instance :)

**Comment by drousseau** [comment]
The "front port" tab count is not updated correctly :

image
